export const FETCH_CUSTOMER_ORDERS = 'FETCH_CUSTOMER_ORDERS';
export const SEARCH_CUSTOMER_ORDERS = 'SEARCH_CUSTOMER_ORDERS';
export const FILTER_CUSTOMER_ORDER = 'FILTER_CUSTOMER_ORDER';
export const ADD_CUSTOMER_ORDER = 'ADD_CUSTOMER_ORDER';
export const UPDATE_CUSTOMER_ORDER = 'UPDATE_CUSTOMER_ORDER';
export const DELETE_CUSTOMER_ORDER = 'DELETE_CUSTOMER_ORDER';
export const EDIT_CUSTOMER_ORDER = 'EDIT_CUSTOMER_ORDER';
export const FIND_CUSTOMER_ORDER_BY_CATEID = 'FIND_CUSTOMER_ORDER_BY_CATEID';


export const FETCH_CATEGORYS = 'FETCH_CATEGORY'; 
export const SAVE_CUSTOMER_ORDER_CODE = 'SAVE_CUSTOMER_ORDER_CODE'; 

export const FETCH_CUSTOMER_ORDERS_FILTER = 'FETCH_CUSTOMER_ORDERS_FILTER';
export const TOTAL_CUSTOMER_ORDERS = 'TOTAL_CUSTOMER_ORDERS';
export const IS_FETCHING = 'IS_FETCHING';