export const FETCH_ORDER_ITEM = 'FETCH_ORDER_ITEM';
export const SEARCH_ORDER_ITEM = 'SEARCH_ORDER_ITEM';
export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';
export const UPDATE_ORDER_ITEM = 'UPDATE_ORDER_ITEM';
export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM';
export const EDIT_ORDER_ITEM = 'EDIT_ORDER_ITEM';