export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const SEARCH_CUSTOMERS = 'SEARCH_CUSTOMERS';
export const FILTER_CUSTOMER = 'FILTER_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const FIND_CUSTOMER_BY_CATEID = 'FIND_CUSTOMER_BY_CATEID';


export const SAVE_CATE_CODE = 'SAVE_CATE_CODE'; 

export const FETCH_CUSTOMERS_FILTER = 'FETCH_CUSTOMERS_FILTER';
export const TOTAL_CUSTOMERS = 'TOTAL_CUSTOMERS';

export const IS_FETCHING_CUSTOMER = 'IS_FETCHING_CUSTOMER';